image: golang:latest

stages:
  - test

golang:1.16:
  image: golang:1.16
  stage: test
  script:
    - go test ./...

test:
  stage: test
  script:
    - go test -coverprofile=coverage.out ./...
  coverage: '/coverage: \d+.\d+% of statements/'
  artifacts:
    when: always
    paths:
      - coverage.out
    expire_in: 1 week

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  tags: [big]
  image: docker:stable
  services: [] # Disable Docker-in-Docker
  artifacts:
    paths: [gl-code-quality-report.json]

staticcheck:
  tags: [big]
  stage: test
  script:
    - go install honnef.co/go/tools/cmd/staticcheck@latest
    - staticcheck ./...
  allow_failure: true
