image: golang:latest

stages:
  - test

golang:1.16:
  image: golang:1.16
  stage: test
  script:
    - go test ./...

test:
  stage: test
  script:
    - go test -coverprofile=coverage.out ./...
  coverage: '/coverage: \d+.\d+% of statements/'
  artifacts:
    when: always
    paths:
      - coverage.out
    expire_in: 1 week

lint:
  image: registry.gitlab.com/gitlab-org/gitlab-build-images:golangci-lint-alpine
  stage: test
  script:
    - golangci-lint run
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json
